services:
  sinatra:
    build: .
    volumes:
      - ./live_audio:/app/live_audio
      - ./live_text:/app/live_text
    environment:
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - WHISPER_API_KEY=${WHISPER_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APP_ENV=${APP_ENV:-'production'}
    ports:
      - "4567:4567"
  livetranslation:
    build: .
    volumes:
      - ./live_audio:/app/live_audio
      - ./live_text:/app/live_text
    environment:
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - WHISPER_API_KEY=${WHISPER_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APP_ENV=${APP_ENV:-'production'}
    entrypoint: ["ruby", "start_rtve_translation.rb", "http://livestream:80/live/hello_720p2628kbs/index.m3u8"]
    restart: "always"
    depends_on:
      livestream:
        condition: service_healthy
  livestream:
    build: nginx
    ports:
      - "1935:1935"
      - "8080:80"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:80/live/hello.m3u8"]
      interval: 5s
      start_period: 30s
      timeout: 2s
