services:
  sinatra:
    build: .
    environment:
      - APP_ENV=${APP_ENV:-'production'}
    ports:
      - "4567:4567"
    volumes:
      - ./live_audio:/app/live_audio
      - ./live_text:/app/live_text
  livetranslation:
    build: .
    environment:
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - WHISPER_API_KEY=${WHISPER_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    entrypoint: ["/bin/sh", "-c", "ruby live_transcriber.rb"]
    volumes:
      - ./live_audio:/app/live_audio
      - ./live_text:/app/live_text
  livestream:
    build: nginx
    environment:
      - STREAM_KEY_NAME=${STREAM_KEY_NAME:-'live'}
    ports:
      - "${RTMP_PORT}:1935"
    volumes:
      - ./live_audio:/opt/data/live_audio
