services:
  sinatra:
    build: .
    volumes:
      - ./live_audio:/app/live_audio
      - ./live_text:/app/live_text
    environment:
      - APP_ENV=${APP_ENV:-'production'}
    ports:
      - "4567:4567"
  livetranslation:
    build: .
    volumes:
      - ./live_audio:/app/live_audio
      - ./live_text:/app/live_text
    environment:
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - WHISPER_API_KEY=${WHISPER_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    entrypoint: ["/bin/sh", "-c", "ruby live_transcriber.rb"]
  livestream:
    build: nginx
    volumes:
      - ./live_audio:/opt/data/live_audio
    ports:
      - "1935:1935"
      - "8080:80"
